export const ICONS = {
  categories: {
    competitive: { emoji: '🏛️', file: 'ic_competitive', gradient: ['#667eea', '#764ba2'] },
    entrance: { emoji: '🎓', file: 'ic_entrance', gradient: ['#f093fb', '#f5576c'] },
    school: { emoji: '📚', file: 'ic_school', gradient: ['#4facfe', '#00f2fe'] },
    university: { emoji: '🏫', file: 'ic_university', gradient: ['#43e97b', '#38f9d7'] },
    placement: { emoji: '💼', file: 'ic_placement', gradient: ['#fa709a', '#fee140'] },
    language: { emoji: '🌐', file: 'ic_language', gradient: ['#a18cd1', '#fbc2eb'] },
    olympiad: { emoji: '🏅', file: 'ic_olympiad', gradient: ['#ffecd2', '#fcb69f'] },
    abroad: { emoji: '✈️', file: 'ic_abroad', gradient: ['#30cfd0', '#330867'] },
  },
  exams: {
    upscCse: { emoji: '🎯', file: 'ic_upsc_cse', color: '#7C3AED' },
    nda: { emoji: '⚔️', file: 'ic_nda', color: '#4C1D95' },
    cds: { emoji: '🎖️', file: 'ic_cds', color: '#5B21B6' },
    sscCgl: { emoji: '📊', file: 'ic_ssc_cgl', color: '#047857' },
    sscChsl: { emoji: '📝', file: 'ic_ssc_chsl', color: '#065F46' },
    sscGd: { emoji: '💪', file: 'ic_ssc_gd', color: '#10B981' },
    police: { emoji: '👮', file: 'ic_police', color: '#1E40AF' },
    sbi: { emoji: '🦁', file: 'ic_sbi', color: '#1D4ED8' },
    rbi: { emoji: '🏧', file: 'ic_rbi', color: '#0369A1' },
    rrbNtpc: { emoji: '🚆', file: 'ic_rrb_ntpc', color: '#D97706' },
    railway: { emoji: '🚂', file: 'ic_railway', color: '#B45309' },
    metro: { emoji: '🚇', file: 'ic_metro', color: '#0284C7' },
    shield: { emoji: '🛡️', file: 'ic_shield', color: '#374151' },
    gear: { emoji: '⚙️', file: 'ic_gear', color: '#4B5563' },
    forest: { emoji: '🌳', file: 'ic_forest', color: '#15803D' },
    wrench: { emoji: '🔧', file: 'ic_wrench', color: '#92400E' },
    bank: { emoji: '🏦', file: 'ic_bank', color: '#1E40AF' },
    nabard: { emoji: '🌾', file: 'ic_nabard', color: '#15803D' },
    sebi: { emoji: '📈', file: 'ic_sebi', color: '#B45309' },
    oil: { emoji: '🛢️', file: 'ic_oil', color: '#92400E' },
    power: { emoji: '⚡', file: 'ic_power', color: '#D97706' },
    bhel: { emoji: '🏭', file: 'ic_bhel', color: '#374151' },
    bel: { emoji: '📡', file: 'ic_bel', color: '#0369A1' },
    isro: { emoji: '🚀', file: 'ic_isro', color: '#7C3AED' },
    nuclear: { emoji: '⚛️', file: 'ic_nuclear', color: '#DC2626' },
    research: { emoji: '🔬', file: 'ic_research', color: '#1D4ED8' },
    bioResearch: { emoji: '🧬', file: 'ic_bio_research', color: '#059669' },
    coastGuard: { emoji: '🌊', file: 'ic_coast_guard', color: '#0284C7' },
    itbp: { emoji: '🏔️', file: 'ic_itbp', color: '#374151' },
    ibAcio: { emoji: '🔍', file: 'ic_ib_acio', color: '#1F2937' },
    ssb: { emoji: '🧠', file: 'ic_ssb', color: '#7C3AED' },
    judiciary: { emoji: '⚖️', file: 'ic_judiciary', color: '#92400E' },
    imd: { emoji: '🌦️', file: 'ic_imd', color: '#0369A1' },
    postal: { emoji: '📮', file: 'ic_postal', color: '#DC2626' },
    fci: { emoji: '🍚', file: 'ic_fci', color: '#D97706' },
    epfo: { emoji: '💰', file: 'ic_epfo', color: '#15803D' },
    medical: { emoji: '🏥', file: 'ic_medical', color: '#DC2626' },
  },
  entrance: {
    neet: { emoji: '🩺', file: 'ic_neet', color: '#059669' },
    gpat: { emoji: '💊', file: 'ic_gpat', color: '#7C3AED' },
    dental: { emoji: '🦷', file: 'ic_dental', color: '#0369A1' },
    ayush: { emoji: '🌿', file: 'ic_ayush', color: '#15803D' },
    design: { emoji: '🎨', file: 'ic_design', color: '#BE185D' },
    nift: { emoji: '👗', file: 'ic_nift', color: '#9D174D' },
    architecture: { emoji: '🏗️', file: 'ic_architecture', color: '#92400E' },
    teacher: { emoji: '👨‍🏫', file: 'ic_teacher', color: '#065F46' },
    hotel: { emoji: '🏨', file: 'ic_hotel', color: '#D97706' },
    ftii: { emoji: '🎬', file: 'ic_ftii', color: '#7C3AED' },
    journalism: { emoji: '📺', file: 'ic_journalism', color: '#0369A1' },
    merchantNavy: { emoji: '🚢', file: 'ic_merchant_navy', color: '#1E40AF' },
    caFinal: { emoji: '🏆', file: 'ic_ca_final', color: '#B45309' },
    iitJam: { emoji: '📐', file: 'ic_iit_jam', color: '#DC2626' },
    gate: { emoji: '🚪', file: 'ic_gate', color: '#0369A1' },
  },
  education: {
    cbse: { emoji: '📘', file: 'ic_cbse', color: '#1D4ED8' },
    icse: { emoji: '📗', file: 'ic_icse', color: '#15803D' },
    stateBoard: { emoji: '📙', file: 'ic_state_board', color: '#D97706' },
    primary: { emoji: '🌱', file: 'ic_primary', color: '#059669' },
    middle: { emoji: '📖', file: 'ic_middle', color: '#0369A1' },
    seniorSec: { emoji: '🎓', file: 'ic_senior_sec', color: '#7C3AED' },
    iit: { emoji: '💻', file: 'ic_iit', color: '#DC2626' },
    iim: { emoji: '💼', file: 'ic_iim', color: '#1D4ED8' },
    nlu: { emoji: '⚖️', file: 'ic_nlu', color: '#92400E' },
    ignou: { emoji: '📡', file: 'ic_ignou', color: '#7C3AED' },
  },
  language: {
    ielts: { emoji: '🇬🇧', file: 'ic_ielts', color: '#1D4ED8' },
    toeflGre: { emoji: '🇺🇸', file: 'ic_toefl_gre', color: '#DC2626' },
    pte: { emoji: '🇦🇺', file: 'ic_pte', color: '#059669' },
    german: { emoji: '🇩🇪', file: 'ic_german', color: '#1F2937' },
    french: { emoji: '🇫🇷', file: 'ic_french', color: '#1D4ED8' },
    jlpt: { emoji: '🇯🇵', file: 'ic_jlpt', color: '#DC2626' },
    topik: { emoji: '🇰🇷', file: 'ic_topik', color: '#0369A1' },
    hsk: { emoji: '🇨🇳', file: 'ic_hsk', color: '#DC2626' },
  },
  tabs: {
    overview: { emoji: '📌', file: 'ic_overview', color: '#6B7280' },
    syllabus: { emoji: '📋', file: 'ic_syllabus', color: '#3B82F6' },
    mockTest: { emoji: '🧪', file: 'ic_mock_test', color: '#F59E0B' },
    answerKey: { emoji: '🔑', file: 'ic_answer_key', color: '#EF4444' },
    updates: { emoji: '📰', file: 'ic_updates', color: '#06B6D4' },
    strategy: { emoji: '🎯', file: 'ic_strategy', color: '#EC4899' },
    interview: { emoji: '🎤', file: 'ic_interview', color: '#F97316' },
  },
  badges: {
    hot: { emoji: '🔥', file: 'ic_hot', bg: 'linear-gradient(135deg,#FF416C,#FF4B2B)' },
    new: { emoji: '✨', file: 'ic_new', bg: 'linear-gradient(135deg,#11998e,#38ef7d)' },
    premium: { emoji: '💎', file: 'ic_premium', bg: 'linear-gradient(135deg,#667eea,#764ba2)' },
    verified: { emoji: '✅', file: 'ic_verified', bg: 'linear-gradient(135deg,#43e97b,#38f9d7)' },
  },
} as const;

export default ICONS;
