import dotenv from 'dotenv';
dotenv.config();

import mongoose from 'mongoose';
import Resource from '../models/Resource';
import Workspace from '../models/Workspace';

const MONGO_URI = process.env.MONGO_URI;

const upsertWorkspace = async (workspace: any) => {
  return Workspace.findOneAndUpdate(
    { slug: workspace.slug },
    { $set: workspace },
    { new: true, upsert: true, runValidators: true }
  );
};

const upsertResource = async (resource: any) => {
  return Resource.findOneAndUpdate(
    { slug: resource.slug },
    { $set: resource },
    { new: true, upsert: true, runValidators: true }
  );
};

const run = async () => {
  if (!MONGO_URI) {
    throw new Error('MONGO_URI is not defined.');
  }

  await mongoose.connect(MONGO_URI);

  const upsc = await upsertWorkspace({
    name: 'UPSC Civil Services',
    shortName: 'UPSC CSE',
    slug: 'upsc-cse',
    type: 'exam',
    category: 'central',
    description: 'Foundation, Prelims, Mains, Interview, NCERT bridge, and current affairs.',
    visibility: 'public',
    status: 'active',
    priority: 100,
    readiness: 70,
    accentColor: '#2563eb',
    template: {
      phases: [
        { key: 'foundation', label: 'Foundation', order: 1 },
        { key: 'prelims', label: 'Prelims', order: 2 },
        { key: 'mains', label: 'Mains', order: 3 },
        { key: 'interview', label: 'Interview', order: 4 },
      ],
      facets: [
        { key: 'stage', label: 'Stage', values: ['foundation', 'prelims', 'mains', 'interview'] },
        { key: 'paper', label: 'Paper', values: ['paper-1', 'paper-2', 'gs1', 'gs2', 'gs3', 'gs4', 'essay', 'optional'] },
        { key: 'subject', label: 'Subject', values: ['history', 'geography', 'polity', 'economy', 'environment', 'csat'] },
      ],
      resourceTypes: ['pyq', 'notes', 'book', 'syllabus', 'qa', 'practice', 'update'],
    },
  });

  const ssc = await upsertWorkspace({
    name: 'SSC Combined Graduate Level',
    shortName: 'SSC CGL',
    slug: 'ssc-cgl',
    type: 'exam',
    category: 'central',
    description: 'Tier 1, Tier 2, Quant, Reasoning, English, and General Awareness.',
    visibility: 'public',
    status: 'active',
    priority: 80,
    readiness: 52,
    accentColor: '#7c3aed',
    template: {
      phases: [
        { key: 'tier-1', label: 'Tier 1', order: 1 },
        { key: 'tier-2', label: 'Tier 2', order: 2 },
      ],
      facets: [
        { key: 'stage', label: 'Tier', values: ['tier-1', 'tier-2'] },
        { key: 'subject', label: 'Subject', values: ['quant', 'reasoning', 'english', 'general-awareness'] },
      ],
      resourceTypes: ['pyq', 'notes', 'practice', 'syllabus', 'update'],
    },
  });

  await upsertWorkspace({
    name: 'CBSE Class 10',
    shortName: 'Class 10',
    slug: 'cbse-class-10',
    type: 'school',
    category: 'school',
    description: 'NCERT books, sample papers, notes, syllabus, and board exam resources.',
    visibility: 'public',
    status: 'coming_soon',
    priority: 50,
    readiness: 35,
    accentColor: '#059669',
    template: {
      phases: [
        { key: 'class-10', label: 'Class 10', order: 1 },
      ],
      resourceTypes: ['book', 'notes', 'pyq', 'syllabus', 'practice'],
    },
  });

  await upsertWorkspace({
    name: 'TCS',
    shortName: 'TCS NQT',
    slug: 'tcs',
    type: 'placement',
    category: 'placement',
    description: 'Single TCS NQT track with Ninja, Digital, and Prime role details inside About.',
    visibility: 'public',
    status: 'coming_soon',
    priority: 45,
    readiness: 30,
    accentColor: '#0891b2',
    template: {
      phases: [
        { key: 'aptitude', label: 'Aptitude', order: 1 },
        { key: 'coding', label: 'Coding', order: 2 },
        { key: 'technical', label: 'Technical', order: 3 },
        { key: 'hr', label: 'HR', order: 4 },
      ],
      resourceTypes: ['qa', 'practice', 'notes', 'pyq'],
    },
  });

  const workspaceCatalog = [
    {
      name: 'UPSC National Defence Academy',
      shortName: 'NDA',
      slug: 'upsc-nda',
      type: 'exam',
      category: 'central',
      description: 'Maths, GAT, previous papers, syllabus, and defence interview prep.',
      status: 'coming_soon',
      priority: 76,
      readiness: 32,
      phases: ['Written', 'SSB'],
      resourceTypes: ['pyq', 'notes', 'syllabus', 'practice', 'qa', 'update'],
    },
    {
      name: 'UPSC Combined Defence Services',
      shortName: 'CDS',
      slug: 'upsc-cds',
      type: 'exam',
      category: 'central',
      description: 'English, GK, maths, OTA papers, SSB, and defence current affairs.',
      status: 'coming_soon',
      priority: 74,
      readiness: 28,
      phases: ['Written', 'SSB'],
      resourceTypes: ['pyq', 'notes', 'syllabus', 'practice', 'qa'],
    },
    {
      name: 'SSC Combined Higher Secondary Level',
      shortName: 'SSC CHSL',
      slug: 'ssc-chsl',
      type: 'exam',
      category: 'central',
      description: 'Tier 1, Tier 2, typing, general awareness, reasoning, quant, and English.',
      status: 'coming_soon',
      priority: 72,
      readiness: 34,
      phases: ['Tier 1', 'Tier 2', 'Typing'],
      resourceTypes: ['pyq', 'notes', 'syllabus', 'practice'],
    },
    {
      name: 'Railway RRB NTPC',
      shortName: 'RRB NTPC',
      slug: 'railway-rrb-ntpc',
      type: 'exam',
      category: 'central',
      description: 'CBT 1, CBT 2, general awareness, maths, reasoning, and previous papers.',
      status: 'coming_soon',
      priority: 70,
      readiness: 31,
      phases: ['CBT 1', 'CBT 2'],
      resourceTypes: ['pyq', 'notes', 'syllabus', 'practice', 'update'],
    },
    {
      name: 'IBPS Probationary Officer',
      shortName: 'IBPS PO',
      slug: 'banking-ibps-po',
      type: 'exam',
      category: 'central',
      description: 'Prelims, mains, banking awareness, quant, reasoning, English, and interview.',
      status: 'coming_soon',
      priority: 68,
      readiness: 29,
      phases: ['Prelims', 'Mains', 'Interview'],
      resourceTypes: ['pyq', 'notes', 'syllabus', 'practice', 'qa', 'update'],
    },
    {
      name: 'GATE Computer Science',
      shortName: 'GATE CSE',
      slug: 'gate-cse',
      type: 'exam',
      category: 'central',
      description: 'CS subjects, aptitude, PYQs, formula notes, mock practice, and PSU preparation.',
      status: 'coming_soon',
      priority: 66,
      readiness: 33,
      phases: ['Foundation', 'PYQ Practice', 'Revision'],
      resourceTypes: ['pyq', 'notes', 'book', 'syllabus', 'practice'],
    },
    {
      name: 'Joint Entrance Examination Main',
      shortName: 'JEE Main',
      slug: 'jee-main',
      type: 'exam',
      category: 'entrance',
      description: 'Physics, chemistry, maths, PYQs, formula sheets, mock practice, and updates.',
      status: 'coming_soon',
      priority: 64,
      readiness: 36,
      phases: ['Physics', 'Chemistry', 'Maths'],
      resourceTypes: ['pyq', 'notes', 'book', 'syllabus', 'practice', 'update'],
    },
    {
      name: 'National Eligibility cum Entrance Test UG',
      shortName: 'NEET UG',
      slug: 'neet-ug',
      type: 'exam',
      category: 'entrance',
      description: 'Physics, chemistry, biology, NCERT bridge, PYQs, and revision material.',
      status: 'coming_soon',
      priority: 63,
      readiness: 36,
      phases: ['Physics', 'Chemistry', 'Biology'],
      resourceTypes: ['pyq', 'notes', 'book', 'syllabus', 'practice', 'update'],
    },
    {
      name: 'Common University Entrance Test UG',
      shortName: 'CUET UG',
      slug: 'cuet-ug',
      type: 'exam',
      category: 'entrance',
      description: 'Domain subjects, language, general test, answer keys, analysis, and updates.',
      status: 'coming_soon',
      priority: 60,
      readiness: 27,
      phases: ['Domain', 'Language', 'General Test'],
      resourceTypes: ['pyq', 'notes', 'syllabus', 'practice', 'update'],
    },
    {
      name: 'Common Admission Test',
      shortName: 'CAT',
      slug: 'cat',
      type: 'exam',
      category: 'entrance',
      description: 'VARC, DILR, QA, previous papers, mocks, and MBA admission updates.',
      status: 'coming_soon',
      priority: 56,
      readiness: 24,
      phases: ['VARC', 'DILR', 'QA'],
      resourceTypes: ['pyq', 'notes', 'practice', 'update'],
    },
    {
      name: 'Central Teacher Eligibility Test',
      shortName: 'CTET',
      slug: 'ctet',
      type: 'exam',
      category: 'teaching',
      description: 'Paper 1, Paper 2, pedagogy, subject notes, PYQs, and eligibility updates.',
      status: 'coming_soon',
      priority: 54,
      readiness: 25,
      phases: ['Paper 1', 'Paper 2'],
      resourceTypes: ['pyq', 'notes', 'syllabus', 'practice', 'update'],
    },
    {
      name: 'Uttar Pradesh Public Service Commission',
      shortName: 'UPPSC',
      slug: 'uppsc',
      type: 'exam',
      category: 'state',
      description: 'State PCS prelims, mains, interview, UP special, and current affairs.',
      status: 'coming_soon',
      priority: 52,
      readiness: 30,
      phases: ['Prelims', 'Mains', 'Interview'],
      resourceTypes: ['pyq', 'notes', 'book', 'syllabus', 'qa', 'practice', 'update'],
    },
    {
      name: 'Bihar Public Service Commission',
      shortName: 'BPSC',
      slug: 'bpsc',
      type: 'exam',
      category: 'state',
      description: 'Prelims, mains, interview, Bihar special, history, geography, polity, and updates.',
      status: 'coming_soon',
      priority: 51,
      readiness: 30,
      phases: ['Prelims', 'Mains', 'Interview'],
      resourceTypes: ['pyq', 'notes', 'book', 'syllabus', 'qa', 'practice', 'update'],
    },
    {
      name: 'Madhya Pradesh Public Service Commission',
      shortName: 'MPPSC',
      slug: 'mppsc',
      type: 'exam',
      category: 'state',
      description: 'State service prelims, mains, interview, MP special notes, and previous papers.',
      status: 'coming_soon',
      priority: 49,
      readiness: 26,
      phases: ['Prelims', 'Mains', 'Interview'],
      resourceTypes: ['pyq', 'notes', 'syllabus', 'practice', 'qa'],
    },
    {
      name: 'Rajasthan Administrative Service',
      shortName: 'RPSC RAS',
      slug: 'rpsc-ras',
      type: 'exam',
      category: 'state',
      description: 'Prelims, mains, Rajasthan special, polity, economy, and interview prep.',
      status: 'coming_soon',
      priority: 48,
      readiness: 25,
      phases: ['Prelims', 'Mains', 'Interview'],
      resourceTypes: ['pyq', 'notes', 'syllabus', 'practice', 'qa'],
    },
    {
      name: 'CBSE Class 12',
      shortName: 'Class 12',
      slug: 'cbse-class-12',
      type: 'school',
      category: 'school',
      description: 'NCERT books, sample papers, board PYQs, syllabus, and stream-wise revision.',
      status: 'coming_soon',
      priority: 43,
      readiness: 35,
      phases: ['Science', 'Commerce', 'Arts'],
      resourceTypes: ['book', 'notes', 'pyq', 'syllabus', 'practice'],
    },
    {
      name: 'NCERT Books and Solutions',
      shortName: 'NCERT',
      slug: 'ncert-books',
      type: 'school',
      category: 'school',
      description: 'Class 6 to 12 NCERT books, solutions, notes, and UPSC foundation bridge.',
      status: 'active',
      priority: 42,
      readiness: 42,
      phases: ['Class 6-8', 'Class 9-10', 'Class 11-12'],
      resourceTypes: ['book', 'notes', 'material', 'practice'],
    },
    {
      name: 'School Olympiads',
      shortName: 'Olympiads',
      slug: 'school-olympiads',
      type: 'school',
      category: 'school',
      description: 'IMO, NSO, IEO, NSTSE, scholarship papers, and class-wise practice.',
      status: 'coming_soon',
      priority: 39,
      readiness: 22,
      phases: ['Maths', 'Science', 'English'],
      resourceTypes: ['pyq', 'notes', 'practice', 'update'],
    },
    {
      name: 'B.Tech Computer Science',
      shortName: 'B.Tech CSE',
      slug: 'btech-cse',
      type: 'college',
      category: 'college',
      description: 'Semester notes, assignments, lab files, previous papers, and placement bridge.',
      status: 'coming_soon',
      priority: 36,
      readiness: 26,
      phases: ['Sem 1-2', 'Sem 3-4', 'Sem 5-6', 'Sem 7-8'],
      resourceTypes: ['pyq', 'notes', 'assignment', 'book', 'practice'],
    },
    {
      name: 'Infosys',
      shortName: 'Infosys',
      slug: 'infosys',
      type: 'placement',
      category: 'placement',
      description: 'Infosys hiring track with SE, DSE, and Power Programmer role details under About.',
      status: 'coming_soon',
      priority: 34,
      readiness: 24,
      phases: ['Aptitude', 'Coding', 'Interview'],
      resourceTypes: ['qa', 'practice', 'notes', 'pyq'],
    },
    {
      name: 'Wipro',
      shortName: 'Wipro',
      slug: 'wipro',
      type: 'placement',
      category: 'placement',
      description: 'Wipro NTH and Elite preparation in one company folder with role details under About.',
      status: 'coming_soon',
      priority: 33,
      readiness: 22,
      phases: ['Aptitude', 'Coding', 'Interview'],
      resourceTypes: ['qa', 'practice', 'notes', 'pyq'],
    },
  ];

  await Promise.all(workspaceCatalog.map(workspace => upsertWorkspace({
    name: workspace.name,
    shortName: workspace.shortName,
    slug: workspace.slug,
    type: workspace.type,
    category: workspace.category,
    description: workspace.description,
    visibility: 'public',
    status: workspace.status,
    priority: workspace.priority,
    readiness: workspace.readiness,
    template: {
      phases: workspace.phases.map((phase, index) => ({
        key: phase.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
        label: phase,
        order: index + 1,
      })),
      facets: [],
      resourceTypes: workspace.resourceTypes,
    },
  })));

  const common = {
    status: 'published',
    visibility: 'public',
    primaryWorkspaceId: upsc._id,
    workspaceIds: [upsc._id],
    stats: { views: 0, saves: 0, downloads: 0 },
  };
  const jee = await Workspace.findOne({ slug: 'jee-main' }).select('_id').lean();
  const neet = await Workspace.findOne({ slug: 'neet-ug' }).select('_id').lean();
  const cbseClass10 = await Workspace.findOne({ slug: 'cbse-class-10' }).select('_id').lean();
  const tcs = await Workspace.findOne({ slug: 'tcs' }).select('_id').lean();

  await Promise.all([
    upsertResource({
      ...common,
      title: 'UPSC CSE Prelims Paper 1',
      slug: 'upsc-cse-prelims-paper-1-2025',
      summary: 'Official GS Paper 1 entry with future analysis, solutions, and syllabus mapping.',
      type: 'pyq',
      subject: 'General Studies',
      year: 2025,
      language: 'english',
      sourceType: 'official',
      sourceName: 'Official PYQ',
      tags: ['upsc', 'prelims', 'gs'],
      facets: { stage: 'prelims', paper: 'paper-1' },
      isFeatured: true,
      updatedFor: '2025',
    }),
    upsertResource({
      ...common,
      title: 'CSAT Aptitude Notes',
      slug: 'upsc-csat-aptitude-notes',
      summary: 'Prelims Paper 2 aptitude, reasoning, comprehension, and maths notes.',
      type: 'notes',
      subject: 'Aptitude',
      language: 'hinglish',
      sourceType: 'platform',
      sourceName: 'Study Hub',
      tags: ['csat', 'aptitude', 'prelims'],
      facets: { stage: 'prelims', paper: 'paper-2' },
      isFeatured: true,
      updatedFor: 'Static core',
    }),
    upsertResource({
      ...common,
      title: 'GS3 Economy Notes: Inclusive Growth',
      slug: 'upsc-gs3-inclusive-growth-notes',
      summary: 'Syllabus-to-resource bridge starter for inclusive growth and related issues.',
      type: 'notes',
      subject: 'Economy',
      topic: 'Inclusive Growth',
      language: 'hinglish',
      sourceType: 'platform',
      sourceName: 'Syllabus mapped',
      tags: ['gs3', 'economy', 'inclusive-growth'],
      facets: { stage: 'mains', paper: 'gs3' },
      syllabusNodes: ['inclusive-growth-and-issues-arising-from-it'],
      isFeatured: true,
      updatedFor: 'Budget 2026 ready',
    }),
    upsertResource({
      ...common,
      title: 'Modern History NCERT Foundation Pack',
      slug: 'modern-history-ncert-foundation-pack',
      summary: 'NCERT bridge for UPSC Foundation and school-level history reading.',
      type: 'book',
      subject: 'History',
      language: 'english',
      sourceType: 'ncert',
      sourceName: 'NCERT Standard',
      tags: ['history', 'ncert', 'foundation'],
      facets: { stage: 'foundation' },
      isFeatured: true,
      updatedFor: 'Static core',
    }),
    upsertResource({
      ...common,
      title: 'DAF Interview Question Bank',
      slug: 'upsc-daf-interview-question-bank',
      summary: 'Interview Q&A flow for state, graduation stream, hobbies, and current affairs.',
      type: 'qa',
      subject: 'Interview',
      language: 'hinglish',
      sourceType: 'platform',
      sourceName: 'DAF personalization',
      tags: ['interview', 'daf', 'qa'],
      facets: { stage: 'interview' },
      isFeatured: true,
      updatedFor: 'Personalized',
    }),
    upsertResource({
      status: 'published',
      visibility: 'public',
      primaryWorkspaceId: ssc._id,
      workspaceIds: [ssc._id],
      stats: { views: 0, saves: 0, downloads: 0 },
      title: 'SSC CGL Tier 1 Quant Previous Paper',
      slug: 'ssc-cgl-tier-1-quant-previous-paper',
      summary: 'Quant paper entry for SSC CGL Tier 1 with practice-first discovery.',
      type: 'pyq',
      subject: 'Quant',
      year: 2024,
      language: 'english',
      sourceType: 'official',
      sourceName: 'Previous paper',
      tags: ['ssc', 'cgl', 'quant'],
      facets: { stage: 'tier-1' },
      isFeatured: false,
      updatedFor: '2024',
    }),
    jee && upsertResource({
      status: 'published',
      visibility: 'public',
      primaryWorkspaceId: jee._id,
      workspaceIds: [jee._id],
      stats: { views: 0, saves: 0, downloads: 0 },
      title: 'JEE Main Physics Previous Paper Set',
      slug: 'jee-main-physics-previous-paper-set',
      summary: 'Physics previous questions organized for topic-wise revision and mock practice.',
      type: 'pyq',
      subject: 'Physics',
      year: 2025,
      language: 'english',
      sourceType: 'official',
      sourceName: 'Previous papers',
      tags: ['jee', 'physics', 'pyq'],
      facets: { stage: 'physics' },
      syllabusNodes: ['mechanics', 'electrodynamics', 'modern-physics'],
      isFeatured: false,
      updatedFor: '2025',
    }),
    neet && upsertResource({
      status: 'published',
      visibility: 'public',
      primaryWorkspaceId: neet._id,
      workspaceIds: [neet._id],
      stats: { views: 0, saves: 0, downloads: 0 },
      title: 'NEET Biology NCERT Revision Notes',
      slug: 'neet-biology-ncert-revision-notes',
      summary: 'NCERT-first biology notes for quick revision, examples, diagrams, and chapter checkpoints.',
      type: 'notes',
      subject: 'Biology',
      language: 'hinglish',
      sourceType: 'ncert',
      sourceName: 'NCERT Standard',
      tags: ['neet', 'biology', 'ncert'],
      facets: { stage: 'biology' },
      syllabusNodes: ['human-physiology', 'genetics', 'ecology'],
      isFeatured: false,
      updatedFor: 'Static core',
    }),
    cbseClass10 && upsertResource({
      status: 'published',
      visibility: 'public',
      primaryWorkspaceId: cbseClass10._id,
      workspaceIds: [cbseClass10._id],
      stats: { views: 0, saves: 0, downloads: 0 },
      title: 'CBSE Class 10 Sample Paper Pack',
      slug: 'cbse-class-10-sample-paper-pack',
      summary: 'Board-style sample papers with syllabus tags for maths, science, social science, and English.',
      type: 'pyq',
      subject: 'Sample Papers',
      year: 2026,
      language: 'english',
      sourceType: 'official',
      sourceName: 'Sample papers',
      tags: ['cbse', 'class-10', 'sample-paper'],
      facets: { stage: 'sample-papers', class: '10' },
      syllabusNodes: ['board-revision', 'sample-paper-practice'],
      isFeatured: false,
      updatedFor: '2026',
    }),
    tcs && upsertResource({
      status: 'published',
      visibility: 'public',
      primaryWorkspaceId: tcs._id,
      workspaceIds: [tcs._id],
      stats: { views: 0, saves: 0, downloads: 0 },
      title: 'TCS NQT Aptitude Practice Questions',
      slug: 'tcs-nqt-aptitude-practice-questions',
      summary: 'Quant, reasoning, verbal, and mock-style practice for TCS NQT preparation.',
      type: 'practice',
      subject: 'Aptitude',
      language: 'hinglish',
      sourceType: 'platform',
      sourceName: 'Placement practice',
      tags: ['tcs', 'nqt', 'aptitude'],
      facets: { stage: 'aptitude', company: 'tcs' },
      syllabusNodes: ['quantitative-aptitude', 'logical-reasoning', 'verbal-ability'],
      isFeatured: false,
      updatedFor: 'Placement core',
    }),
  ]);

  console.log('Study Hub seed completed.');
};

run()
  .catch(error => {
    console.error('Study Hub seed failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await mongoose.disconnect();
  });
