import type { StudyCardGoalType, StudyCardTone } from '../models/StudyCard';

export type StudyHubPlacementSpec = {
  category: string;
  family: string;
  exam: string;
  icon: string;
  goalType?: StudyCardGoalType;
  branches: string[];
  aliases?: string[];
  tone?: StudyCardTone;
};

const premiumExecutiveBranches = [
  'Start Here / Company Snapshot',
  'Start Here / Role Tracks',
  'Start Here / Round Wise Playbook',
  'Start Here / Daily Drill Sheet',
  'Previous Year Papers / Difficulty Wise Sets',
  'Previous Year Papers / Timed Practice Sets',
  'Study Material / Premium Handbook',
  'Study Material / Mini Projects',
  'Interview / Project Deep Dive',
  'Interview / Communication Scripts',
  'Resume / Portfolio Checklist',
  'Strategy / Interview Day Checklist',
  'Strategy / Offer HR Negotiation',
];

const serviceCoreBranches = [
  'Overview',
  'Start Here / Premium Roadmap',
  'Start Here / Weekly Study Plan',
  'Start Here / Progress Tracker',
  ...premiumExecutiveBranches,
  'About / Roles',
  'About / Eligibility',
  'About / Recruitment Process',
  'Syllabus / Aptitude',
  'Syllabus / Coding',
  'Syllabus / Technical Interview',
  'Syllabus / Communication Round',
  'Previous Year Papers / Aptitude Questions',
  'Previous Year Papers / Coding Questions',
  'Previous Year Papers / Interview Experiences',
  'Previous Year Papers / Topic Wise Practice',
  'Previous Year Papers / Solutions',
  'Previous Year Papers / Answer Keys',
  'Study Material / Quantitative Aptitude',
  'Study Material / Logical Reasoning',
  'Study Material / Verbal Ability',
  'Study Material / Programming Logic',
  'Study Material / CS Fundamentals',
  'Study Material / DBMS SQL',
  'Study Material / OS CN OOPs',
  'Study Material / Formula Sheets',
  'Study Material / Revision Notes',
  'Study Material / Cheat Sheets',
  'Coding / Easy Problems',
  'Coding / Medium Problems',
  'Coding / Company Pattern Problems',
  'Coding / Solved Programs',
  'Technical / C C++ Java Python',
  'Technical / Project Discussion',
  'Communication / Email Writing',
  'Communication / Speaking Practice',
  'Interview / Technical Q&A',
  'Interview / HR Q&A',
  'Interview / Managerial Round',
  'Interview / STAR Stories',
  'Resume / ATS Format',
  'Resume / Project Bullet Bank',
  'Resume / LinkedIn Profile',
  'Mock Tests / Sectional Tests',
  'Mock Tests / Full Length Tests',
  'Mock Tests / Coding Mocks',
  'Mock Tests / Communication Mocks',
  'Strategy / 30 Day Plan',
  'Strategy / Last Week Revision',
  'Strategy / Mistake Tracker',
  'Updates',
];

const productCoreBranches = [
  'Overview',
  'Start Here / Premium Roadmap',
  'Start Here / Weekly Study Plan',
  'Start Here / Progress Tracker',
  ...premiumExecutiveBranches,
  'About / Roles',
  'About / Eligibility',
  'About / Hiring Process',
  'Syllabus / DSA',
  'Syllabus / CS Fundamentals',
  'Syllabus / System Design',
  'Syllabus / Behavioral Round',
  'Previous Year Papers / Online Assessment',
  'Previous Year Papers / Coding Interview',
  'Previous Year Papers / Interview Experiences',
  'Previous Year Papers / Topic Wise Practice',
  'Previous Year Papers / Solutions',
  'Previous Year Papers / Answer Keys',
  'Study Material / DSA Patterns',
  'Study Material / CS Fundamentals',
  'Study Material / OOP LLD',
  'Study Material / HLD System Design',
  'Study Material / Formula Sheets',
  'Study Material / Revision Notes',
  'Study Material / Cheat Sheets',
  'DSA / Arrays Strings',
  'DSA / Linked List Stack Queue',
  'DSA / Trees Graphs',
  'DSA / Dynamic Programming',
  'DSA / Greedy Heap',
  'DSA / Company Tagged Problems',
  'DSA / Solved Patterns',
  'Coding / Online Assessment Practice',
  'Coding / Interview Problems',
  'Coding / Debugging Rounds',
  'Technical / OS DBMS CN',
  'Technical / Project Discussion',
  'Interview / Technical Deep Dive',
  'Interview / Behavioral STAR',
  'Interview / Hiring Manager Round',
  'Resume / Product Resume',
  'Resume / Project Bullet Bank',
  'Resume / LinkedIn Profile',
  'Mock Tests / OA Mocks',
  'Mock Tests / Coding Interview Mocks',
  'Mock Tests / System Design Mocks',
  'Strategy / 45 Day Plan',
  'Strategy / Last Week Revision',
  'Strategy / Mistake Tracker',
  'Updates',
];

const commonPrepBranches = [
  'Overview',
  'Start Here / Premium Roadmap',
  'Start Here / Weekly Study Plan',
  'Start Here / Progress Tracker',
  ...premiumExecutiveBranches,
  'Syllabus / Complete Placement Roadmap',
  'Syllabus / Aptitude',
  'Syllabus / DSA',
  'Syllabus / CS Core',
  'Previous Year Papers / Service Based Practice',
  'Previous Year Papers / Product Based OA Practice',
  'Previous Year Papers / Interview Experiences',
  'Previous Year Papers / Topic Wise Practice',
  'Previous Year Papers / Solutions',
  'Previous Year Papers / Answer Keys',
  'Study Material / Aptitude Notes',
  'Study Material / DSA Sheets',
  'Study Material / CS Core Notes',
  'Study Material / System Design Notes',
  'Study Material / Formula Sheets',
  'Study Material / Revision Notes',
  'Study Material / Cheat Sheets',
  'DSA Sheets / Striver A2Z Sheet',
  'DSA Sheets / NeetCode 150',
  'DSA Sheets / Love Babbar 450',
  'DSA Sheets / Blind 75',
  'DSA Topics / Arrays',
  'DSA Topics / Strings',
  'DSA Topics / Linked List',
  'DSA Topics / Stack Queue',
  'DSA Topics / Trees',
  'DSA Topics / Graphs',
  'DSA Topics / Dynamic Programming',
  'DSA Topics / Binary Search',
  'DSA Topics / Bit Manipulation',
  'DSA Topics / Greedy',
  'DSA Topics / Heap Priority Queue',
  'CS Core / Operating Systems',
  'CS Core / DBMS & SQL',
  'CS Core / Computer Networks',
  'CS Core / OOPs',
  'System Design / High Level Design',
  'System Design / Low Level Design',
  'Aptitude / Quantitative',
  'Aptitude / Logical Reasoning',
  'Aptitude / Verbal Ability',
  'Resume / Templates ATS Friendly',
  'Resume / How to Write',
  'Resume / Project Ideas',
  'Interview / HR Questions',
  'Interview / Behavioral STAR Method',
  'Interview / Salary Negotiation',
  'LinkedIn Optimization Guide',
  'Off Campus Guide / How to Apply',
  'Mock Tests / Aptitude',
  'Mock Tests / Coding',
  'Mock Tests / Interview',
  'Mock Tests / Communication',
  'Placement Tracker / Application Tracker',
  'Placement Tracker / Company Shortlist',
  'Placement Tracker / Interview Pipeline',
  'Placement Tracker / Offer Comparison',
  'Placement Tracker / Mistake Log',
  'Placement Tracker / Revision Calendar',
];

const makeServiceCompanySpec = (input: {
  exam: string;
  aliases: string[];
  roleBranch: string;
  extraBranches?: string[];
}): StudyHubPlacementSpec => ({
  category: 'Placement / Private',
  family: 'Service Based IT',
  exam: input.exam,
  icon: 'placement',
  aliases: input.aliases,
  branches: [input.roleBranch, ...serviceCoreBranches, ...(input.extraBranches || [])],
});

const makeProductCompanySpec = (input: {
  exam: string;
  aliases: string[];
  roleBranch: string;
  extraBranches?: string[];
}): StudyHubPlacementSpec => ({
  category: 'Placement / Private',
  family: 'Product Based',
  exam: input.exam,
  icon: 'placement',
  tone: 'cyan',
  aliases: input.aliases,
  branches: [input.roleBranch, ...productCoreBranches, ...(input.extraBranches || [])],
});

export const detailedPlacementSpecs: StudyHubPlacementSpec[] = [
  makeServiceCompanySpec({
    exam: 'TCS',
    aliases: ['Tata Consultancy Services', 'TCS NQT', 'TCS Ninja', 'TCS Digital', 'TCS Prime', 'TCS Recruitment', 'TCS Off Campus'],
    roleBranch: 'About / Ninja Digital Prime',
    extraBranches: ['Previous Year Papers / TCS iON Practice', 'Strategy / How to Clear NQT', 'Study Material / TCS NQT Pattern'],
  }),
  makeServiceCompanySpec({
    exam: 'Infosys',
    aliases: ['Infosys SE', 'Infosys DSE', 'Infosys SP', 'Infosys InfyTQ', 'Infosys Recruitment'],
    roleBranch: 'About / SE DSE SP',
    extraBranches: ['Previous Year Papers / InfyTQ Practice', 'Study Material / Pseudocode', 'Strategy / Infosys Assessment'],
  }),
  makeServiceCompanySpec({
    exam: 'Wipro',
    aliases: ['Wipro Elite', 'Wipro Turbo', 'Wipro NLTH', 'Wipro NTH', 'Wipro Recruitment', 'Wipro Off Campus'],
    roleBranch: 'About / Elite Turbo NTH',
    extraBranches: ['Study Material / Written Communication', 'Strategy / Wipro NTH Plan'],
  }),
  makeServiceCompanySpec({
    exam: 'Cognizant',
    aliases: ['Cognizant GenC', 'Cognizant Elevate', 'Cognizant Next', 'CTS Recruitment', 'Cognizant Technology Solutions'],
    roleBranch: 'About / GenC Elevate Next',
    extraBranches: ['Study Material / Automata Fix', 'Syllabus / SDET Assessment'],
  }),
  makeServiceCompanySpec({
    exam: 'Accenture',
    aliases: ['Accenture ASE', 'Accenture Advanced ASE', 'Accenture Recruitment', 'Accenture Off Campus', 'Accenture Technology'],
    roleBranch: 'About / ASE Advanced ASE',
    extraBranches: ['Study Material / Cognitive Assessment', 'Study Material / Communication Assessment'],
  }),
  makeServiceCompanySpec({
    exam: 'Capgemini',
    aliases: ['Capgemini Exceller', 'Capgemini Analyst', 'Capgemini Recruitment', 'Capgemini Off Campus'],
    roleBranch: 'About / Analyst Senior Analyst',
    extraBranches: ['Study Material / Game Based Aptitude', 'Study Material / Essay Writing'],
  }),
  makeServiceCompanySpec({
    exam: 'Deloitte',
    aliases: ['Deloitte USI', 'Deloitte Analyst', 'Deloitte Consulting', 'Deloitte Campus', 'Deloitte Off Campus'],
    roleBranch: 'About / Analyst Consultant',
    extraBranches: ['Study Material / Case Based Reasoning', 'Interview / Consulting Fit Questions'],
  }),
  makeServiceCompanySpec({
    exam: 'HCLTech',
    aliases: ['HCL', 'HCL Technologies', 'HCLTech Recruitment', 'HCLTech Off Campus', 'HCL First Careers'],
    roleBranch: 'About / Graduate Engineer Trainee',
    extraBranches: ['Study Material / HCL Aptitude Pattern', 'Interview / Project Discussion'],
  }),
  makeServiceCompanySpec({
    exam: 'Tech Mahindra',
    aliases: ['TechM', 'Tech Mahindra Recruitment', 'Tech Mahindra Off Campus', 'Tech Mahindra ELTP'],
    roleBranch: 'About / Associate Software Engineer',
    extraBranches: ['Study Material / Communication Skills', 'Study Material / Automata Coding'],
  }),
  makeServiceCompanySpec({
    exam: 'LTIMindtree',
    aliases: ['LTI', 'Mindtree', 'Larsen Toubro Infotech', 'LTIMindtree Recruitment', 'LTIMindtree Off Campus'],
    roleBranch: 'About / Graduate Engineer Trainee',
    extraBranches: ['Study Material / Adaptive Aptitude', 'Interview / Managerial Round'],
  }),
  makeServiceCompanySpec({
    exam: 'IBM',
    aliases: ['IBM India', 'IBM Associate System Engineer', 'IBM Consulting', 'IBM Recruitment', 'IBM Off Campus'],
    roleBranch: 'About / Associate System Engineer',
    extraBranches: ['Study Material / Cognitive Ability', 'Study Material / Business Communication'],
  }),
  makeServiceCompanySpec({
    exam: 'Persistent Systems',
    aliases: ['Persistent', 'Persistent Recruitment', 'Persistent Off Campus', 'Persistent Martian Program'],
    roleBranch: 'About / Software Engineer',
    extraBranches: ['Study Material / Martian Program Prep', 'Coding / Java OOP Practice'],
  }),
  makeServiceCompanySpec({
    exam: 'Mphasis',
    aliases: ['Mphasis Recruitment', 'Mphasis Off Campus', 'Mphasis Trainee Software Engineer'],
    roleBranch: 'About / Trainee Software Engineer',
    extraBranches: ['Study Material / AMCAT Pattern', 'Interview / Client Readiness'],
  }),
  makeServiceCompanySpec({
    exam: 'Hexaware',
    aliases: ['Hexaware Technologies', 'Hexaware Recruitment', 'Hexaware Off Campus', 'Hexaware GET'],
    roleBranch: 'About / Graduate Engineer Trainee',
    extraBranches: ['Study Material / Versant Communication', 'Study Material / Logical Programming'],
  }),
  makeServiceCompanySpec({
    exam: 'EY GDS',
    aliases: ['EY', 'Ernst Young GDS', 'EY Global Delivery Services', 'EY Analyst', 'EY Campus'],
    roleBranch: 'About / Analyst Technology Consultant',
    extraBranches: ['Study Material / Case Study Round', 'Interview / Consulting Stories'],
  }),
  makeServiceCompanySpec({
    exam: 'PwC',
    aliases: ['PwC India', 'PwC AC', 'PricewaterhouseCoopers', 'PwC Analyst', 'PwC Campus'],
    roleBranch: 'About / Analyst Associate',
    extraBranches: ['Study Material / Case Interview Basics', 'Interview / Business Fit Questions'],
  }),
  makeServiceCompanySpec({
    exam: 'KPMG',
    aliases: ['KPMG India', 'KPMG Global Services', 'KPMG Analyst', 'KPMG Campus'],
    roleBranch: 'About / Analyst Associate Consultant',
    extraBranches: ['Study Material / Business Aptitude', 'Interview / Consulting Fit Questions'],
  }),
  makeServiceCompanySpec({
    exam: 'Virtusa',
    aliases: ['Virtusa Consulting', 'Virtusa Recruitment', 'Virtusa Off Campus'],
    roleBranch: 'About / Associate Engineer',
    extraBranches: ['Study Material / Java SQL Prep', 'Interview / Client Project Discussion'],
  }),
  makeProductCompanySpec({
    exam: 'Amazon',
    aliases: ['Amazon SDE', 'Amazon Software Engineer', 'Amazon Bangalore', 'Amazon Hyderabad', 'Amazon OA', 'Amazon Interview', 'AWS Jobs'],
    roleBranch: 'About / SDE SDE-II',
    extraBranches: ['Leadership Principles / All 16 LPs', 'Leadership Principles / STAR Answers', 'Behavioral Interview / Customer Obsession'],
  }),
  makeProductCompanySpec({
    exam: 'Microsoft',
    aliases: ['Microsoft SDE', 'Microsoft Software Engineer', 'MSFT India', 'Microsoft Hyderabad', 'Microsoft Bangalore', 'Microsoft Internship'],
    roleBranch: 'About / SDE Intern FTE',
    extraBranches: ['Study Material / Microsoft Tagged DSA', 'Behavioral Interview / Growth Mindset'],
  }),
  makeProductCompanySpec({
    exam: 'Google',
    aliases: ['Google SWE', 'Google Software Engineer', 'Google Bangalore', 'Google Hyderabad', 'Google STEP Intern', 'Alphabet Jobs India'],
    roleBranch: 'About / STEP L3 L4',
    extraBranches: ['Behavioral Interview / Googleyness', 'Study Material / Google Tagged DSA', 'System Design / Large Scale Basics'],
  }),
  makeProductCompanySpec({
    exam: 'Adobe',
    aliases: ['Adobe SDE', 'Adobe MTS', 'Adobe Software Engineer', 'Adobe India', 'Adobe Noida', 'Adobe Bangalore'],
    roleBranch: 'About / MTS Software Engineer',
    extraBranches: ['Study Material / OOP Design', 'Study Material / Computer Graphics Basics'],
  }),
  makeProductCompanySpec({
    exam: 'Oracle',
    aliases: ['Oracle OCI', 'Oracle Software Engineer', 'Oracle India', 'Oracle Campus Recruitment'],
    roleBranch: 'About / Member Technical Staff',
    extraBranches: ['Study Material / SQL PL SQL', 'System Design / Cloud Basics'],
  }),
  makeProductCompanySpec({
    exam: 'Zoho',
    aliases: ['Zoho Software Developer', 'Zoho Programmer Analyst', 'Zoho Campus Drive', 'Zoho Off Campus'],
    roleBranch: 'About / Developer Programmer Analyst',
    extraBranches: ['Syllabus / Zoho Written Round', 'Study Material / Pattern Printing', 'Coding / Advanced Programming Round'],
  }),
  makeProductCompanySpec({
    exam: 'Flipkart',
    aliases: ['Flipkart SDE', 'Flipkart Software Engineer', 'Flipkart Grid', 'Flipkart Interview'],
    roleBranch: 'About / SDE Intern FTE',
    extraBranches: ['Study Material / E-Commerce System Design', 'Strategy / Flipkart Grid Prep'],
  }),
  makeProductCompanySpec({
    exam: 'Meesho',
    aliases: ['Meesho Engineer', 'Meesho SDE', 'Meesho Software Engineer', 'Meesho Off Campus'],
    roleBranch: 'About / SDE Backend Frontend',
    extraBranches: ['Study Material / Marketplace System Design', 'Behavioral Interview / Ownership Stories'],
  }),
  makeProductCompanySpec({
    exam: 'Swiggy',
    aliases: ['Swiggy Tech', 'Swiggy SDE', 'Swiggy Software Engineer', 'Swiggy Instamart'],
    roleBranch: 'About / SDE Backend Frontend',
    extraBranches: ['Study Material / Delivery System Design', 'System Design / Location Search Basics'],
  }),
  makeProductCompanySpec({
    exam: 'PhonePe',
    aliases: ['PhonePe SDE', 'PhonePe Software Engineer', 'PhonePe Backend Engineer', 'PhonePe Off Campus'],
    roleBranch: 'About / SDE Backend',
    extraBranches: ['Study Material / Fintech System Design', 'Study Material / Transactions Consistency'],
  }),
  makeProductCompanySpec({
    exam: 'Razorpay',
    aliases: ['Razorpay Engineer', 'Razorpay SDE', 'Razorpay Software Engineer', 'Razorpay Backend Engineer'],
    roleBranch: 'About / SDE Backend',
    extraBranches: ['Study Material / Payment Gateway Design', 'Study Material / API Design'],
  }),
  makeProductCompanySpec({
    exam: 'Atlassian',
    aliases: ['Atlassian SDE', 'Atlassian Software Engineer', 'Atlassian India', 'Atlassian Remote'],
    roleBranch: 'About / Backend Frontend SDE',
    extraBranches: ['Study Material / Collaboration System Design', 'Behavioral Interview / Values Round'],
  }),
  makeProductCompanySpec({
    exam: 'Salesforce',
    aliases: ['Salesforce SDE', 'Salesforce Developer', 'Salesforce India', 'Salesforce Campus'],
    roleBranch: 'About / Software Engineer Developer',
    extraBranches: ['Study Material / CRM System Design', 'Study Material / Java Apex Basics'],
  }),
  makeProductCompanySpec({
    exam: 'Intuit',
    aliases: ['Intuit SDE', 'Intuit Software Engineer', 'Intuit India', 'Intuit Campus'],
    roleBranch: 'About / Software Engineer',
    extraBranches: ['Study Material / Fintech Product Design', 'Behavioral Interview / Customer Benefit'],
  }),
  makeProductCompanySpec({
    exam: 'SAP Labs',
    aliases: ['SAP', 'SAP Labs India', 'SAP Developer', 'SAP Software Engineer'],
    roleBranch: 'About / Developer Associate',
    extraBranches: ['Study Material / ERP Cloud Basics', 'Study Material / Java SQL OOP'],
  }),
  makeProductCompanySpec({
    exam: 'Walmart Global Tech',
    aliases: ['Walmart Labs', 'Walmart Global Technology', 'Walmart SDE', 'Walmart Software Engineer'],
    roleBranch: 'About / SDE Backend',
    extraBranches: ['Study Material / Retail Scale Design', 'System Design / Inventory Basics'],
  }),
  makeProductCompanySpec({
    exam: 'Uber',
    aliases: ['Uber SDE', 'Uber Software Engineer', 'Uber India', 'Uber Backend Engineer'],
    roleBranch: 'About / SDE Backend',
    extraBranches: ['Study Material / Ride Matching Design', 'System Design / Geospatial Basics'],
  }),
  makeProductCompanySpec({
    exam: 'Zomato',
    aliases: ['Zomato SDE', 'Zomato Tech', 'Zomato Software Engineer', 'Blinkit Tech'],
    roleBranch: 'About / SDE Backend Frontend',
    extraBranches: ['Study Material / Food Delivery Design', 'System Design / Search Ranking Basics'],
  }),
  makeProductCompanySpec({
    exam: 'Paytm',
    aliases: ['Paytm SDE', 'Paytm Software Engineer', 'Paytm Payments', 'Paytm Backend Engineer'],
    roleBranch: 'About / SDE Backend',
    extraBranches: ['Study Material / Wallet Payments Design', 'Study Material / Transaction Safety'],
  }),
  makeProductCompanySpec({
    exam: 'CRED',
    aliases: ['CRED SDE', 'CRED Software Engineer', 'CRED Backend Engineer', 'CRED Android'],
    roleBranch: 'About / SDE Backend Mobile',
    extraBranches: ['Study Material / Rewards System Design', 'Study Material / API Contracts'],
  }),
  {
    category: 'Placement / Private',
    family: 'Common Preparation',
    exam: 'DSA & Placement Prep',
    icon: 'coding',
    goalType: 'resource_folder',
    tone: 'violet',
    aliases: ['Placement Preparation', 'Campus Placement Guide', 'SDE Preparation', 'Software Engineer Interview', 'Coding Interview Prep', 'LeetCode Preparation', 'Technical Interview Guide'],
    branches: commonPrepBranches,
  },
];
