import type { StudyCardGoalType, StudyCardTone } from '../models/StudyCard';

export type StudyHubUniversitySpec = {
  category: string;
  family: string;
  exam: string;
  icon: string;
  goalType?: StudyCardGoalType;
  branches: string[];
  aliases?: string[];
  tone?: StudyCardTone;
};

const universityResourceShelves = [
  'Syllabus',
  'Previous Year Papers',
  'Study Material',
];

const practicalResourceShelves = universityResourceShelves;

const withResourceShelves = (basePaths: string[], shelves = universityResourceShelves) =>
  Array.from(new Set(basePaths.flatMap((basePath) => shelves.map((shelf) => `${basePath} / ${shelf}`))));

const semesterResourceBranches = universityResourceShelves;

const officialSourceBranches = [
  'Official Sources / Syllabus',
  'Official Sources / Previous Year Papers',
  'Official Sources / Study Material',
  'Official Sources / Exam Notices',
  'Official Sources / Results',
];

const artsCommerceScienceBranches = withResourceShelves([
  'BA / English',
  'BA / Hindi',
  'BA / History',
  'BA / Political Science',
  'BA / Economics',
  'BA / Psychology',
  'BSc / Mathematics',
  'BSc / Physics',
  'BSc / Chemistry',
  'BSc / Computer Science',
  'BSc / Botany',
  'BSc / Zoology',
  'BCom / General',
  'BCom / Honours',
  'BBA BMS',
  'BCA',
  'MA / Subject-wise',
  'MSc / Subject-wise',
  'MCom',
  'MBA',
  'MCA',
  'PhD Coursework / Research Methodology',
]);

const engineeringProgramBranches = withResourceShelves([
  'BTech / First Year Common',
  'BTech / Computer Science and Engineering',
  'BTech / Information Technology',
  'BTech / Artificial Intelligence and Data Science',
  'BTech / Electronics and Communication Engineering',
  'BTech / Electrical Engineering',
  'BTech / Mechanical Engineering',
  'BTech / Civil Engineering',
  'BTech / Chemical Engineering',
  'MTech / Computer Science and Engineering',
  'MTech / Electronics and Communication Engineering',
  'MBA',
  'MCA',
  'Diploma / Mechanical Engineering',
  'Diploma / Electrical Engineering',
], practicalResourceShelves);

const gkvFetProgramBranches = withResourceShelves([
  'BTech / First Year Common',
  'BTech / Computer Science and Engineering',
  'BTech / Electronics and Communication Engineering',
  'BTech / Electrical Engineering',
  'BTech / Mechanical Engineering',
  'MTech / Computer Science and Engineering',
  'MTech / Electronics and Communication Engineering',
  'Diploma / Mechanical Engineering',
  'Diploma / Electrical Engineering',
  'PhD / Computer Science / Coursework',
  'PhD / Electronics / Coursework',
  'PhD / Mechanical Engineering / Coursework',
], practicalResourceShelves);

const gkvEngineeringBranches = gkvFetProgramBranches.map((branch) => `Faculty of Engineering and Technology / ${branch}`);

const healthScienceProgramBranches = withResourceShelves([
  'MBBS',
  'BDS',
  'BAMS BHMS BUMS',
  'BPharm',
  'BSc Nursing',
  'Paramedical',
  'MD MS / Specialty-wise',
  'MDS / Specialty-wise',
  'PhD Coursework / Research Methodology',
]);

const lawProgramBranches = [
  ...withResourceShelves([
    'BA LLB',
    'BBA LLB',
    'LLB 3 Year',
    'LLM',
    'PhD Coursework / Research Methodology',
  ]),
  'Moot Court / Memorials',
  'Case Law Notes',
  'Bare Acts',
];

const universityCoreBranches = [
  'About University',
  'Admissions / Notices',
  'Examination / Date Sheet',
  'Examination / Results',
  ...officialSourceBranches,
];

export const detailedUniversitySpecs: StudyHubUniversitySpec[] = [
  {
    category: 'University Exams',
    family: 'Common Entrances',
    exam: 'CUET UG',
    icon: 'university',
    aliases: ['Common University Entrance Test', 'NTA CUET', 'Central University Admission', 'DU Admission via CUET', 'BHU Admission CUET', 'JNU Admission CUET', 'CUET 2025'],
    branches: ['Overview', 'Syllabus / Language Tests 13 Languages', 'Syllabus / Domain Subjects All 27', 'Syllabus / General Test', 'Previous Year Papers / 2024', 'Previous Year Papers / 2023', 'Previous Year Papers / 2022', 'Study Material / General Test', 'Study Material / English', 'Study Material / Hindi', 'Study Material / Mathematics', 'Study Material / Physics', 'Study Material / Chemistry', 'Study Material / Biology', 'Study Material / Accountancy', 'Study Material / Business Studies', 'Study Material / Economics', 'Study Material / History', 'Study Material / Geography', 'Study Material / Political Science', 'Study Material / Sociology', 'Study Material / Psychology', 'Study Material / Computer Science', 'Mock Tests / General Test', 'Mock Tests / Domain Subject-wise', 'Answer Keys', 'Strategy / University Cut-off Guide', 'Strategy / Subject Combination Guide', 'Updates / Notification', 'Updates / Admit Card', 'Updates / Result', 'University Preference Guide'],
  },
  {
    category: 'University Exams',
    family: 'Common Entrances',
    exam: 'CUET PG',
    icon: 'university',
    aliases: ['CUET Postgraduate', 'NTA CUET PG', 'Central University PG Admission', 'MA Entrance Central University', 'MSc Entrance Central University'],
    branches: ['Overview', 'Syllabus / Subject-wise PG', 'Previous Year Papers / Subject-wise', 'Study Material / General Paper', 'Study Material / Domain Subject-wise', 'Mock Tests', 'Answer Keys', 'Strategy', 'Updates'],
  },
  {
    category: 'University Exams',
    family: 'Common Entrances',
    exam: 'IIT JAM',
    icon: 'iit-jam',
    aliases: ['Joint Admission Test for MSc', 'IIT MSc Entrance', 'IISc MSc Entrance', 'JAM Mathematics', 'JAM Physics', 'JAM Chemistry', 'MSc Entrance IIT'],
    branches: ['Overview', 'Syllabus / Mathematics MA', 'Syllabus / Physics PH', 'Syllabus / Chemistry CY', 'Syllabus / Statistics ST', 'Syllabus / Biotechnology BT', 'Syllabus / Economics EN', 'Syllabus / Geology GG', 'Previous Year Papers / Mathematics', 'Previous Year Papers / Physics', 'Previous Year Papers / Chemistry', 'Previous Year Papers / Statistics', 'Previous Year Papers / Biotechnology', 'Previous Year Papers / Economics', 'Study Material / Mathematics', 'Study Material / Physics', 'Study Material / Chemistry', 'Study Material / Statistics', 'Study Material / Biotechnology', 'Study Material / Economics', 'Mock Tests / Subject-wise', 'Answer Keys', 'Strategy', 'Updates'],
  },
  {
    category: 'University Exams',
    family: 'Common Entrances',
    exam: 'JEST',
    icon: 'research',
    aliases: ['Joint Entrance Screening Test', 'JEST Physics', 'TIFR Entrance', 'IISc PhD Entrance', 'SNBNCBS Entrance', 'Research Institute PhD'],
    branches: ['Overview', 'Syllabus / Physics', 'Syllabus / Theoretical Computer Science', 'Syllabus / Neuroscience', 'Previous Year Papers / Physics', 'Previous Year Papers / TCS', 'Study Material / Physics', 'Study Material / Theoretical CS', 'Mock Tests', 'Answer Keys', 'Strategy', 'Updates'],
  },
  {
    category: 'University Exams',
    family: 'Common Entrances',
    exam: 'TIFR GS',
    icon: 'research',
    aliases: ['Tata Institute of Fundamental Research', 'TIFR Graduate School', 'TIFR PhD Admission', 'TIFR Research Fellowship'],
    branches: ['Overview', 'Syllabus / Physics', 'Syllabus / Chemistry', 'Syllabus / Mathematics', 'Syllabus / Computer Science', 'Syllabus / Biology', 'Previous Year Papers / Physics', 'Previous Year Papers / Mathematics', 'Previous Year Papers / Computer Science', 'Study Material / Physics', 'Study Material / Mathematics', 'Study Material / Computer Science', 'Mock Tests', 'Strategy', 'Updates'],
  },
  {
    category: 'University Exams',
    family: 'Delhi University',
    exam: 'DU UG Programs',
    icon: 'university',
    aliases: ['Delhi University UG', 'DU Undergraduate', 'University of Delhi', 'DU BA', 'DU BSc', 'DU BCom', 'DU Colleges', 'SOL DU'],
    branches: [
      'About DU CUET Admission',
      ...withResourceShelves([
        'BA / English Honours',
        'BA / Hindi Honours',
        'BA / History Honours',
        'BA / Political Science Honours',
        'BA / Economics Honours',
        'BA / Sociology Honours',
        'BA / Psychology Honours',
        'BA / Philosophy Honours',
        'BA / Programme',
        'BSc / Mathematics Honours',
        'BSc / Physics Honours',
        'BSc / Chemistry Honours',
        'BSc / Computer Science Honours',
        'BSc / Statistics Honours',
        'BCom / Honours',
        'BCom / Programme',
        'BBA / FIA',
      ]),
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'Delhi University',
    exam: 'DU PG Programs',
    icon: 'university',
    aliases: ['DU PG', 'Delhi University Postgraduate', 'MA Entrance DU', 'MSc DU'],
    branches: [
      'Overview',
      ...withResourceShelves([
        'MA / English',
        'MA / Hindi',
        'MA / History',
        'MA / Political Science',
        'MA / Economics',
        'MA / Sociology',
        'MSc / Mathematics',
        'MSc / Physics',
        'MSc / Chemistry',
        'MSc / Computer Science',
        'MCom',
      ]),
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'BHU',
    exam: 'BHU Programs',
    icon: 'university',
    aliases: ['Banaras Hindu University', 'BHU Varanasi', 'BHU UET', 'BHU PET', 'Kashi Hindu Vishwavidyalaya'],
    branches: [
      'About BHU',
      'Entrance / CUET UG',
      'Entrance / CUET PG',
      'Entrance / RET PhD',
      ...withResourceShelves([
        'BA / Subject-wise',
        'BSc / Mathematics',
        'BSc / Physics',
        'BSc / Chemistry',
        'BCom',
        'BEd',
        'MA / Subject-wise',
        'MSc / Subject-wise',
        'MCom',
        'MBBS',
        'BDS',
        'BTech / Department-wise Institute Level',
      ], practicalResourceShelves),
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'IGNOU',
    exam: 'IGNOU Programs',
    icon: 'ignou',
    aliases: ['IGNOU All Programs', 'Indira Gandhi National Open University', 'IGNOU BA', 'IGNOU BCom', 'IGNOU MBA', 'IGNOU MCA', 'IGNOU BEd', 'IGNOU Assignments', 'IGNOU TEE', 'IGNOU Term End Exam', 'Distance Education IGNOU', 'Open Learning IGNOU'],
    branches: [
      'About IGNOU',
      ...withResourceShelves([
        'BA BAG',
        'BCom BCOMG',
        'BSc',
        'BCA',
        'BBA',
        'BEd',
        'BSW',
        'MA / Subject-wise',
        'MCom',
        'MBA',
        'MCA',
        'MSc / Subject-wise',
        'MEd',
        'Diploma / Program-wise',
        'Certificate / Program-wise',
        'PhD Coursework',
      ]),
      'Study Material / Block-wise Downloads',
      'Assignments / Current Session TEE',
      'Assignments / Previous Sessions',
      'Previous Term End Papers / June 2025',
      'Previous Term End Papers / December 2024',
      'Previous Term End Papers / June 2024',
      'Previous Term End Papers / December 2023',
      'Previous Term End Papers / Older',
      'Practical Files / BCA MCA CS',
      'Project Guidelines / MBA MEd',
      'Grade Card Guide',
      'Exam Date Sheet',
      ...officialSourceBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'Engineering Universities',
    exam: 'AKTU Programs',
    icon: 'gear',
    aliases: ['Dr. APJ Abdul Kalam Technical University', 'AKTU Lucknow', 'UPTU Old Name', 'UP Engineering University', 'AKTU BTech', 'AKTU Affiliated Colleges'],
    branches: ['About AKTU', 'Affiliated Colleges / Engineering Colleges', 'Affiliated Colleges / Management Colleges', ...engineeringProgramBranches, ...universityCoreBranches],
  },
  {
    category: 'University Exams',
    family: 'Engineering Universities',
    exam: 'VTU Programs',
    icon: 'gear',
    aliases: ['Visvesvaraya Technological University', 'VTU Belagavi', 'Karnataka Engineering University', 'VTU BTech', 'VTU Affiliated Colleges'],
    branches: ['About VTU', 'Affiliated Colleges / Engineering Colleges', 'Schemes / CBCS and NEP', ...engineeringProgramBranches, ...universityCoreBranches],
  },
  {
    category: 'University Exams',
    family: 'Engineering Universities',
    exam: 'Anna University Programs',
    icon: 'gear',
    aliases: ['Anna University Chennai', 'Tamil Nadu Engineering University', 'Anna University BTech', 'Anna University Affiliated Colleges', 'CEG MIT AC Guindy'],
    branches: ['About Anna University', 'Constituent Colleges / CEG MIT ACT SAP', 'Affiliated Colleges / Engineering Colleges', 'Regulations / 2021', 'Regulations / 2017', ...engineeringProgramBranches, ...universityCoreBranches],
  },
  {
    category: 'University Exams',
    family: 'State Universities',
    exam: 'University of Mumbai Programs',
    icon: 'gear',
    aliases: ['University of Mumbai', 'Mumbai University Programs', 'Mumbai University Engineering', 'MU Engineering', 'Mumbai University Arts Commerce', 'MU Exams'],
    branches: ['About University of Mumbai', 'Affiliated Colleges / Arts Commerce Science', 'Affiliated Colleges / Engineering', ...artsCommerceScienceBranches, ...engineeringProgramBranches, ...universityCoreBranches],
  },
  {
    category: 'University Exams',
    family: 'Engineering Universities',
    exam: 'Delhi Technical Universities and IPU',
    icon: 'gear',
    aliases: ['DTU', 'Delhi Technological University', 'NSUT', 'Netaji Subhas University of Technology', 'IGDTUW', 'Indraprastha University', 'GGSIPU', 'IP University', 'Delhi Engineering Colleges'],
    branches: [
      ...withResourceShelves([
        'DTU / BTech / Computer Science and Engineering',
        'DTU / BTech / Information Technology',
        'DTU / BTech / Electronics and Communication Engineering',
        'DTU / BTech / Electrical Engineering',
        'DTU / BTech / Mechanical Engineering',
        'DTU / BTech / Civil Engineering',
        'NSUT / BTech / Computer Science and Engineering',
        'NSUT / BTech / Information Technology',
        'NSUT / BTech / Electronics and Communication Engineering',
        'NSUT / BTech / Electrical Engineering',
        'NSUT / BTech / Mechanical Engineering',
        'IGDTUW / BTech / Computer Science and Engineering',
        'IGDTUW / BTech / Information Technology',
        'IGDTUW / BTech / Electronics and Communication Engineering',
        'GGSIPU / BTech / Computer Science and Engineering',
        'GGSIPU / BTech / Information Technology',
        'GGSIPU / BTech / Electronics and Communication Engineering',
        'GGSIPU / BTech / Electrical Engineering',
        'GGSIPU / BTech / Mechanical Engineering',
        'GGSIPU / BTech / Civil Engineering',
      ], practicalResourceShelves),
      ...withResourceShelves([
        'GGSIPU / BCA',
        'GGSIPU / BBA',
        'GGSIPU / BCom',
        'GGSIPU / MBA',
        'GGSIPU / MCA',
      ]),
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'Engineering Universities',
    exam: 'GKV Faculty of Engineering and Technology',
    icon: 'gear',
    aliases: ['GKV FET', 'Gurukula Kangri FET', 'Gurukul Kangri FET', 'GKV BTech', 'GKV Engineering', 'Gurukula Kangri Engineering', 'Gurukula Kangri BTech'],
    branches: [
      'About GKV FET',
      'Departments / Computer Science and Engineering',
      'Departments / Electronics and Communication Engineering',
      'Departments / Electrical Engineering',
      'Departments / Mechanical Engineering',
      ...gkvFetProgramBranches,
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'Engineering Universities',
    exam: 'State Technical University Programs',
    icon: 'gear',
    aliases: ['RGPV', 'GTU', 'MAKAUT', 'JNTU', 'BPUT', 'RTU', 'IKGPTU', 'HPTU', 'State Technical Universities', 'Engineering College Semester Exams'],
    branches: [
      'RGPV Bhopal / BTech MCA MBA',
      'Gujarat Technological University / BTech Diploma MBA',
      'MAKAUT West Bengal / BTech BCA BBA',
      'JNTU Hyderabad / BTech MTech MBA',
      'JNTU Kakinada / BTech MTech MBA',
      'BPUT Odisha / BTech MTech MBA',
      'Rajasthan Technical University / BTech MTech MBA',
      'IKGPTU Punjab / BTech BCA MBA',
      'HPTU Himachal / BTech BPharm MBA',
      ...engineeringProgramBranches,
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'IITs',
    exam: 'IIT Programs',
    icon: 'iit',
    aliases: ['Indian Institutes of Technology', 'IIT BTech', 'IIT MTech via GATE', 'IIT Bombay', 'IIT Delhi', 'IIT Madras', 'IIT Kanpur', 'IIT Kharagpur', 'IIT Roorkee', 'IIT Guwahati', 'Other IITs'],
    branches: [
      'Institute Index / IIT Bombay',
      'Institute Index / IIT Delhi',
      'Institute Index / IIT Madras',
      'Institute Index / IIT Kanpur',
      'Institute Index / IIT Kharagpur',
      'Institute Index / IIT Roorkee',
      'Institute Index / IIT Guwahati',
      'Institute Index / Other IITs',
      ...withResourceShelves([
        'BTech / First Year Common',
        'BTech / Computer Science and Engineering',
        'BTech / Electronics and Communication Engineering',
        'BTech / Electrical Engineering',
        'BTech / Mechanical Engineering',
        'BTech / Civil Engineering',
        'BTech / Chemical Engineering',
        'BTech / Aerospace Engineering',
        'BTech / Metallurgical Engineering',
        'MTech / Department-wise',
        'MSc / Subject-wise',
        'Dual Degree / Department-wise',
      ], practicalResourceShelves),
      'Lecture Notes / NPTEL Mapping',
      'Project Report Templates',
      'CGPA Calculator Guide',
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'IITs / NITs / IIITs',
    exam: 'NIT Programs',
    icon: 'iit',
    aliases: ['National Institutes of Technology', 'NIT BTech', 'NIT MTech', 'NIT Trichy', 'NIT Surathkal', 'NIT Warangal', 'NIT Rourkela', 'NIT Calicut', 'NIT Kurukshetra', 'NIT Colleges'],
    branches: [
      'Institute Index / NIT Trichy',
      'Institute Index / NIT Surathkal',
      'Institute Index / NIT Warangal',
      'Institute Index / NIT Rourkela',
      'Institute Index / NIT Calicut',
      'Institute Index / NIT Kurukshetra',
      'Institute Index / NIT Durgapur',
      'Institute Index / Other NITs',
      ...engineeringProgramBranches,
      ...withResourceShelves([
        'MSc / Mathematics',
        'MSc / Physics',
        'MSc / Chemistry',
        'MBA',
      ]),
      'Lecture Notes / NPTEL Mapping',
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'IITs / NITs / IIITs',
    exam: 'IIIT and IISc IISER Programs',
    icon: 'iit',
    aliases: ['IIIT Programs', 'Indian Institutes of Information Technology', 'IISc Bangalore', 'IISER', 'IIIT Hyderabad', 'IIIT Delhi', 'IIIT Allahabad', 'IIIT Bangalore'],
    branches: [
      'Institute Index / IIIT Hyderabad',
      'Institute Index / IIIT Delhi',
      'Institute Index / IIIT Allahabad',
      'Institute Index / IIIT Bangalore',
      'Institute Index / Other IIITs',
      'Institute Index / IISc Bangalore',
      'Institute Index / IISER System',
      ...engineeringProgramBranches,
      ...withResourceShelves([
        'IISc Bangalore / BTech / Mathematics and Computing',
        'IISc Bangalore / MTech / Department-wise',
        'IISc Bangalore / MSc / Subject-wise',
        'IISER System / BS MS / Sciences',
        'Research Programs / Coursework',
      ]),
      'Lecture Notes / NPTEL Mapping',
      'Assignments / Programming and Labs',
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'IIMs',
    exam: 'IIM Programs',
    icon: 'iim',
    aliases: ['Indian Institutes of Management', 'IIM MBA', 'IIM Ahmedabad PGP', 'IIM Bangalore PGP', 'IIM Calcutta PGP', 'IIM Lucknow PGP', 'IIM Indore PGP', 'Top 6 IIM'],
    branches: ['IIM System 21 IIMs', 'PGP MBA / Term 1-6', 'PGP MBA / Core Subjects', 'PGP MBA / Finance', 'PGP MBA / Marketing', 'PGP MBA / Operations', 'PGP MBA / HR', 'PGP MBA / Strategy', 'PGP MBA / Economics', 'PGP MBA / Quantitative Methods', 'PGPX Executive MBA', 'FPM PhD', 'Case Study Material', 'Interview Prep / WAT PI', 'Summer Internship Guide', 'Previous Papers / Mid Term End Term'],
  },
  {
    category: 'University Exams',
    family: 'Central Universities',
    exam: 'Central University Program Hub',
    icon: 'university',
    aliases: ['Central Universities India', 'JNU', 'AMU', 'JMI', 'HCU', 'University of Hyderabad', 'Pondicherry University', 'Tezpur University', 'NEHU', 'Visva Bharati', 'Central University Semester Exams'],
    branches: [
      'JNU / Schools and Centres',
      'JNU / Previous Year Papers',
      'JNU / Syllabus',
      'AMU / UG PG Programs',
      'AMU / Question Papers',
      'AMU / Syllabus',
      'JMI / UG PG Programs',
      'JMI / Syllabus',
      'JMI / Examination Notices',
      'University of Hyderabad / UG PG Research',
      'Pondicherry University / UG PG Research',
      'Tezpur University / UG PG Research',
      'NEHU Shillong / UG PG Research',
      'Visva Bharati / UG PG Research',
      'Central University of Rajasthan / UG PG Research',
      'Central University of Haryana / UG PG Research',
      'Central University of Jharkhand / UG PG Research',
      'Central University of Kerala / UG PG Research',
      'Central University of Himachal Pradesh / UG PG Research',
      'Mahatma Gandhi Central University / UG PG Research',
      ...artsCommerceScienceBranches,
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'State Universities',
    exam: 'North India State University Programs',
    icon: 'university',
    aliases: ['State Universities North India', 'Lucknow University', 'CSJMU Kanpur', 'Allahabad University', 'Patna University', 'Magadh University', 'Rajasthan University', 'Punjabi University', 'Kumaun University', 'HNB Garhwal University'],
    branches: [
      'Uttar Pradesh / Lucknow University',
      'Uttar Pradesh / CSJMU Kanpur',
      'Uttar Pradesh / MGKVP Varanasi',
      'Uttar Pradesh / Dr Bhimrao Ambedkar University Agra',
      'Uttar Pradesh / Deen Dayal Upadhyaya Gorakhpur University',
      'Bihar / Patna University',
      'Bihar / Magadh University',
      'Bihar / Lalit Narayan Mithila University',
      'Rajasthan / University of Rajasthan',
      'Rajasthan / Jai Narain Vyas University',
      'Punjab / Punjabi University Patiala',
      'Punjab / Panjab University Chandigarh',
      'Haryana / Kurukshetra University',
      'Uttarakhand / Kumaun University',
      'Uttarakhand / HNB Garhwal University',
      ...artsCommerceScienceBranches,
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'State Universities',
    exam: 'West Central and East State University Programs',
    icon: 'university',
    aliases: ['State Universities Central India', 'Madhya Pradesh Universities', 'Maharashtra Universities', 'Gujarat Universities', 'Odisha Universities', 'West Bengal Universities', 'Jharkhand Universities', 'Chhattisgarh Universities'],
    branches: [
      'Madhya Pradesh / DAVV Indore',
      'Madhya Pradesh / Barkatullah University',
      'Madhya Pradesh / Jiwaji University',
      'Maharashtra / Savitribai Phule Pune University',
      'Maharashtra / Rashtrasant Tukadoji Maharaj Nagpur University',
      'Maharashtra / Shivaji University',
      'Gujarat / Gujarat University',
      'Gujarat / Sardar Patel University',
      'West Bengal / University of Calcutta',
      'West Bengal / Jadavpur University',
      'West Bengal / University of Burdwan',
      'Odisha / Utkal University',
      'Jharkhand / Ranchi University',
      'Chhattisgarh / Pt Ravishankar Shukla University',
      ...artsCommerceScienceBranches,
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'State Universities',
    exam: 'South and North East State University Programs',
    icon: 'university',
    aliases: ['State Universities South India', 'Kerala University', 'Calicut University', 'Madras University', 'Bharathiar University', 'Osmania University', 'Andhra University', 'Gauhati University'],
    branches: [
      'Tamil Nadu / University of Madras',
      'Tamil Nadu / Bharathiar University',
      'Tamil Nadu / Bharathidasan University',
      'Tamil Nadu / Madurai Kamaraj University',
      'Kerala / University of Kerala',
      'Kerala / University of Calicut',
      'Kerala / Mahatma Gandhi University',
      'Karnataka / Bangalore University',
      'Karnataka / Mysore University',
      'Telangana / Osmania University',
      'Telangana / Kakatiya University',
      'Andhra Pradesh / Andhra University',
      'Andhra Pradesh / Sri Venkateswara University',
      'Assam / Gauhati University',
      'Assam / Dibrugarh University',
      'Manipur / Manipur University',
      'Tripura / Tripura University',
      ...artsCommerceScienceBranches,
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'State Universities',
    exam: 'Affiliated and Autonomous College Program Hub',
    icon: 'university',
    aliases: ['Government Colleges', 'Autonomous Colleges', 'Affiliated Colleges', 'College Semester Exams', 'College PYQ', 'College Syllabus'],
    branches: [
      'Government Colleges / Arts Commerce Science',
      'Autonomous Colleges / CBCS NEP Syllabus',
      'Private Affiliated Colleges / Semester Exams',
      'Minority Colleges / Program-wise',
      'Women Colleges / Program-wise',
      'Even Semester / Papers and Syllabus',
      'Odd Semester / Papers and Syllabus',
      'Internal Assessment / Assignments',
      'Practical Exams / Files and Viva',
      ...artsCommerceScienceBranches,
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'Deemed Universities',
    exam: 'Deemed and Private University Programs',
    icon: 'university',
    aliases: ['Deemed Universities India', 'BITS Pilani', 'VIT', 'SRM', 'Manipal', 'Amrita', 'Symbiosis', 'KIIT', 'Thapar', 'Christ University', 'Private University Semester Exams'],
    branches: [
      'Institution Index / BITS Pilani',
      'Institution Index / VIT',
      'Institution Index / SRM Institute',
      'Institution Index / Manipal Academy',
      'Institution Index / Amrita Vishwa Vidyapeetham',
      'Institution Index / Symbiosis International',
      'Institution Index / KIIT',
      'Institution Index / Thapar Institute',
      'Institution Index / Christ University',
      'Institution Index / Banasthali Vidyapith',
      'Institution Index / Gurukula Kangri Vishwavidyalaya',
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'Open Universities',
    exam: 'State Open University Programs',
    icon: 'ignou',
    aliases: ['State Open Universities', 'YCMOU', 'VMOU', 'NSOU', 'BRAOU', 'UPRTOU', 'MP Bhoj Open University', 'Nalanda Open University', 'KKHSOU', 'Distance Education'],
    branches: [
      'YCMOU Maharashtra / UG PG Diploma',
      'VMOU Kota / UG PG Diploma',
      'NSOU West Bengal / UG PG Diploma',
      'BRAOU Telangana / UG PG Diploma',
      'UPRTOU Prayagraj / UG PG Diploma',
      'MP Bhoj Open University / UG PG Diploma',
      'Nalanda Open University / UG PG Diploma',
      'KKHSOU Assam / UG PG Diploma',
      'Tamil Nadu Open University / UG PG Diploma',
      'Karnataka State Open University / UG PG Diploma',
      'Study Material / Block-wise Downloads',
      'Assignments / Current Session',
      'Term End Papers / Session-wise',
      'Project Guidelines / Program-wise',
      ...artsCommerceScienceBranches,
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'Agricultural Universities',
    exam: 'ICAR and Agricultural University Programs',
    icon: 'environment',
    aliases: ['Agricultural Universities', 'ICAR Universities', 'SAU', 'BSc Agriculture', 'BVSc', 'BTech Food Technology', 'Agriculture College Exams'],
    branches: [
      'ICAR AIEEA / UG PG PhD',
      'IARI Delhi / UG PG Research',
      'GBPUAT Pantnagar / Agriculture Veterinary Engineering',
      'PAU Ludhiana / Agriculture Veterinary',
      'CCS HAU Hisar / Agriculture Veterinary',
      'MPKV Rahuri / Agriculture',
      'TNAU Coimbatore / Agriculture Horticulture',
      'UAS Bangalore / Agriculture',
      'ANGRAU Andhra Pradesh / Agriculture',
      'OUAT Odisha / Agriculture Veterinary',
      ...withResourceShelves([
        'BSc Agriculture',
        'BSc Horticulture',
        'BVSc AH',
        'BTech Food Technology',
        'MSc Agriculture / Discipline-wise',
        'PhD Coursework / Research Methodology',
      ]),
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'Medical Universities',
    exam: 'AIIMS MBBS MD Programs',
    icon: 'medical',
    aliases: ['AIIMS Delhi', 'AIIMS MBBS', 'AIIMS PG', 'All India Institute of Medical Sciences', 'Medical College Exams'],
    branches: ['AIIMS System 19 Institutes', 'MBBS Year 1 / Anatomy', 'MBBS Year 1 / Physiology', 'MBBS Year 1 / Biochemistry', 'MBBS Year 2 / Pathology', 'MBBS Year 2 / Pharmacology', 'MBBS Year 2 / Microbiology', 'MBBS Year 2 / Forensic Medicine', 'MBBS Year 3 / Medicine', 'MBBS Year 3 / Surgery', 'MBBS Year 3 / OBG', 'MBBS Year 3 / Pediatrics', 'MBBS Year 3 / Orthopedics', 'MBBS Year 4 Final / All Clinical Subjects', 'MBBS Year 4 Final / Community Medicine', 'MD MS Programs / All Specialties', 'Previous Year Papers / Pre Clinicals', 'Previous Year Papers / Para Clinicals', 'Previous Year Papers / Clinicals', 'Notes / All Subjects', 'Image Based Questions / Radiology Pathology', 'Clinical Cases / Medicine Surgery'],
  },
  {
    category: 'University Exams',
    family: 'Medical Universities',
    exam: 'State Health Science University Programs',
    icon: 'medical',
    aliases: ['Medical Universities India', 'MUHS', 'RGUHS', 'KNRUHS', 'WBUHS', 'RUHS', 'ABVMU', 'Medical College Semester Exams', 'Nursing University Exams'],
    branches: [
      'MUHS Maharashtra / Medical Dental Nursing Pharmacy',
      'RGUHS Karnataka / Medical Dental Nursing Pharmacy',
      'KNRUHS Telangana / Medical Dental Nursing',
      'WBUHS West Bengal / Medical Dental Nursing',
      'RUHS Rajasthan / Medical Dental Nursing Pharmacy',
      'ABVMU Uttar Pradesh / Nursing Paramedical',
      'Atal Medical and Research University Himachal / Medical Nursing',
      ...healthScienceProgramBranches,
      'Previous Year Papers / Pre Clinical',
      'Previous Year Papers / Para Clinical',
      'Previous Year Papers / Clinical',
      'Practical Viva / Subject-wise',
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'Law Universities',
    exam: 'NLU Programs',
    icon: 'nlu',
    aliases: ['National Law University', 'NLU BA LLB', 'NLU LLM', 'NLSIU', 'NALSAR', 'NLU Delhi', 'WBNUJS', 'Law School Exams'],
    branches: [
      'Institute Index / NLU System',
      'Institute Index / NLSIU Bengaluru',
      'Institute Index / NALSAR Hyderabad',
      'Institute Index / NLU Delhi',
      'Institute Index / WBNUJS Kolkata',
      ...lawProgramBranches,
      ...withResourceShelves([
        'Subjects / Constitutional Law',
        'Subjects / Law of Contract',
        'Subjects / Law of Torts',
        'Subjects / Criminal Law IPC CrPC',
        'Subjects / Family Law Hindu Muslim',
        'Subjects / Property Law',
        'Subjects / Company Law',
        'Subjects / Administrative Law',
        'Subjects / Environmental Law',
        'Subjects / International Law',
        'Subjects / IPR',
        'Subjects / Labour Law',
        'Subjects / Evidence Law',
        'Subjects / Jurisprudence',
      ]),
      'Moot Court Material',
      'Legal Research Methods',
      'Important Case Laws',
      'Bare Acts Collection',
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'Law Universities',
    exam: 'Law College and University Programs',
    icon: 'nlu',
    aliases: ['Faculty of Law DU', 'Jamia Law', 'BHU Law', 'AMU Law', 'Government Law Colleges', 'Law College Semester Exams'],
    branches: [
      'DU Faculty of Law / LLB LLM',
      'BHU Faculty of Law / BA LLB LLB LLM',
      'AMU Faculty of Law / BA LLB LLM',
      'JMI Faculty of Law / BA LLB LLM',
      'Government Law Colleges / State-wise',
      'Private Law Colleges / University-wise',
      ...lawProgramBranches,
      ...universityCoreBranches,
    ],
  },
  {
    category: 'University Exams',
    family: 'PG Entrances',
    exam: 'University PG Entrance Hub',
    icon: 'university',
    aliases: ['PG Entrance Exams', 'Masters Entrance Exams', 'University Postgraduate Admissions', 'MSc Entrance', 'MA Entrance', 'MCom Entrance', 'MCA Entrance', 'PhD Entrance'],
    branches: [
      'CUET PG / Subject-wise',
      'IIT JAM / MSc Subjects',
      'GATE / MTech and PSU',
      'UGC NET JRF / Humanities Commerce',
      'CSIR NET JRF / Science Subjects',
      'NIMCET / MCA Entrance',
      'TISS CUET PG / Social Sciences',
      'JEST / Physics TCS Neuroscience',
      'TIFR GS / Science Research',
      'NBHM / Mathematics',
      'ICMR JRF / Life Science Social Science',
      'DBT JRF / Biotechnology',
      'GPAT / Pharmacy PG',
      'INI CET / Medical PG',
      'NEET PG / Medical PG',
      'LLM Entrances / CLAT PG AILET PG',
      'Syllabus / Subject-wise',
      'Previous Year Papers / Subject-wise',
      'Study Material / Subject-wise',
      'Mock Tests / Subject-wise',
      'Answer Keys / Official',
      'Updates / Notification',
    ],
  },
  {
    category: 'University Exams',
    family: 'University Entrance Tests',
    exam: 'University Entrance Test Hub',
    icon: 'university',
    aliases: ['University Entrance Tests', 'College Entrance Tests', 'UG Entrance Exams', 'PG Entrance Tests', 'Admission Test Papers'],
    branches: [
      'CUET UG / Domain Subjects',
      'CUET PG / Subject-wise',
      'IPU CET / UG PG Programs',
      'TANCET / MBA MCA ME MTech',
      'MAH CET / MBA MCA Law',
      'AP PGCET / PG Programs',
      'TS PGCET / PG Programs',
      'Karnataka PGCET / MBA MCA MTech',
      'Kerala CEE / KEAM and PG',
      'WB JECA JELET PGET / Professional Programs',
      'JMI Entrance / UG PG',
      'AMU Entrance / UG PG',
      'BHU Admission / UG PG RET',
      'JNU Admission / CUET and PhD',
      'Syllabus / Exam-wise',
      'Previous Year Papers / Exam-wise',
      'Study Material / Exam-wise',
      'Mock Tests / Exam-wise',
      'Answer Keys / Official',
      'Updates / Notification',
    ],
  },
  {
    category: 'University Exams',
    family: 'Deemed Universities',
    exam: 'Gurukula Kangri Vishwavidyalaya',
    icon: 'university',
    aliases: ['GKV Programs', 'Gurukula Kangri Deemed to be University', 'Gurukul Kangri University', 'Gurukula Kangri University', 'GKV Haridwar', 'GKDU', 'GKV', 'Kanya Gurukula Campus'],
    branches: [
      'About Gurukula Kangri Vishwavidyalaya',
      'Campuses / Haridwar Main Campus',
      'Campuses / Kanya Gurukula Campus Dehradun',
      'Campuses / Kanya Gurukula Campus Haridwar',
      ...gkvEngineeringBranches,
      ...withResourceShelves([
        'Faculty of Technology / Computer Science / BCA',
        'Faculty of Technology / Computer Science / MCA',
        'Faculty of Sciences / BSc / Mathematics',
        'Faculty of Sciences / BSc / Physics',
        'Faculty of Sciences / BSc / Chemistry',
        'Faculty of Sciences / MSc / Mathematics',
        'Faculty of Sciences / MSc / Physics',
        'Faculty of Sciences / MSc / Chemistry',
        'Faculty of Life Sciences / BSc / Botany',
        'Faculty of Life Sciences / BSc / Zoology',
        'Faculty of Life Sciences / MSc / Microbiology',
        'Faculty of Life Sciences / MSc / Environmental Science',
        'Faculty of Management Studies / BBA',
        'Faculty of Management Studies / BCom',
        'Faculty of Management Studies / MBA',
        'Faculty of Management Studies / MBA Business Finance',
        'Faculty of Management Studies / MBA Business Economics',
        'Faculty of Medical Science and Health / BPharm',
        'Faculty of Yoga and Physical Education / Yoga',
        'Faculty of Yoga and Physical Education / BPES BPEd',
        'Faculty of Humanities / BA / English',
        'Faculty of Humanities / BA / Hindi',
        'Faculty of Humanities / BA / Psychology',
        'Faculty of Humanities / MA / English',
        'Faculty of Humanities / MA / Hindi',
        'Faculty of Humanities / MA / Psychology',
        'Faculty of Oriental Studies / BA / Sanskrit',
        'Faculty of Oriental Studies / MA / Sanskrit',
        'Faculty of Oriental Studies / MA / Veda',
        'Faculty of Oriental Studies / MA / Philosophy',
        'Faculty of Oriental Studies / AIHC and Archaeology',
      ]),
      ...universityCoreBranches,
    ],
  },
];
